### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LDoESpro87** [Danilo1301/GTASA_libGiroflexVSL#1]
My game crashes when cleo loading. I tried to remove giroflex.csa and giroflex.fxt, and my game working. I tested it on Alyn's client v2 and single player GTA SA.

**Comment by Danilo1301** [comment]
I made a new update trying to fix some crashes
If it still doesn't work, send here the giroflex.log (inside the config folder)

**Comment by LDoESpro87** [comment]
> I made a new update trying to fix some crashes If it still doesn't work, send here the giroflex.log (inside the config folder)

Bro, fully working! Wonderful work!

**Comment by Danilo1301** [comment]
Thanks!
