### ISSUE TITLE
Não consigo entrar no gta

### ISSUE THREAD

**Issue by Jonasapk** [Danilo1301/GTASA_libGiroflexVSL#7]
Abaixei a nova versão do giroflex e meu gta não quer mais abrir ele fica em um carregamento infinito em tela preta

**Comment by Danilo1301** [comment]
Coloca as libs necessárias
O GiroflexVSL.csa na pasta do jogo e a libGiroflexVSL.so na pasta mods

Se não funcionar, tira todos os mods cleos e .so
Tenta instalar só o giroflex pra ver

Qualquer coisa entra no Discord

**Comment by Jonasapk** [comment]
Ok vou instalar de novo e não funciona eu entro no Discord
